project:
  type: website

website:
  title: "Quantum Experiments"
  favicon: favicon.png
  navbar:
    logo : pngegg.png
    right:
      - text: "About"
        href:  about.qmd
      - icon: github
        href: https://github.com/Prashantmdgl9
      - icon: person
        href: https://drive.google.com/file/d/1vfFJpnEj6LuaJel8izQWQElQKF9Acs37/view?usp=drive_link
      - text: "ML Blog"
        href: https://prashantmdgl9.github.io/ml_experiments/

      
format:
  html:
    theme: cosmo
    css: styles.css

